### ISSUE TITLE
Normalized Brain: think for 1 move (2 plies)

### ISSUE THREAD

**Issue by lrozenblyum** [lrozenblyum/chess#235]
For years the chess brain were able to think just for 1 ply.
See #130 

Let's extend the thinking possibilities and dig deeper (at least into 1 move).

**Expectation**:
- [x] we can select an optimal move by taking into account possible opponent's responses (best ones)
- [x] make sure terminal positions are handled correctly
- [x] command line parameters should be accepted for the thinking depth (1, 2)
- [x] Denormalized brain: split to #294 
- [x] Normalized brain should be affected
  - [x] Evaluator stages introduced #178 
  - [x] Validate source in [ 0, 1 ] range
  - [x] Remove Checkmate evaluator from next stages since it's used initially
    - [x] Rebranded to Terminal evaluator
    - [x] Respect draw condition: causes #299 
  - [x] We may extract PositionInterface (or Supplier<List<Move>>?) to process just it
  - [x] Brain should be made generic-specific again, to prevent changing the clients too much
  - [x] Non-terminal evaluation works
  - [x] Terminal evaluation for balanced tree
  - [x] Terminal + non-terminal possibilities
     - [x] Make evaluators symmetrical: split to #280 
  - [x] Logging
    - [x] Handle the [ ] somehow?
    - [x] If we use LegalPlayer with depth 1, check if the logs are logical
  - [x] Provide string representation correctly depending on the depth (name method)
- [x] Simple brain should be NOT affected
- [x] Simulator should prove 2 is better than 1
  - [x] Red test
  - [x] Make it green
- [x] Test infrastructure should support nice and simple tree input (maybe from string representation) - the goal is unclear, not needed now
- [x] Generate further tasks (like thinking for any number of plies, improve architecture etc)
- [x] Performance - it's slow (not a big surprise). Not THAT slow (removed Sysouts) - split to #300

**Not a goal**:
* no optimization should be done at this stage

**Possible complexities**:
* existing algorithm has 1 ply depth (an odd number), thinking for 2 plies means thinking for an even number.
