### ISSUE TITLE
Make evaluators symmetrical

### ISSUE THREAD

**Issue by lrozenblyum** [lrozenblyum/chess#293]
Caused by #235 which showed an idea that for most correct comparison of evaluation results on different levels of the tree, we need comparable numbers.
It might mean that every evaluator should check not only OUR but the OPPONENT situation.
E.g. attack evaluator checks attackIndex(our) - attackIndex(opponent) and so on.

Split to #323 
  _This may lead us to finally removing the concept of Position + Move evaluation and go to Position 
  evaluation.
  Which may improve performance (due to reduced need of position.move generation)_

At the moment some of our evaluators aren't symmetrical so that thinking for the 2'nd ply doesn't provide logical results because it analyzes different aspect of the position.
So as a matter of fact we compare uncomparable things.
For example castling safety for our side and castling safety for the opponent are totally different.
- [ ] We should make all evaluators analyze our and enemy position thus making them symmetrical
   - [x] Think about generalizing 'index' calculation for us and the opponent
   - [x] Castling safety is totally NOT symmetrical. Initially developed in #131 
       - [x] Make it symmetrical
       - [x] Ensure Normalized constraints are kept
       - [x] Migrate to Normalized package
       - [x] Should Position be enriched by getOccupiedSquares?
       - [x] At the moment after king movement all moves are 0.5 which causes king movement itself evaluate fine but logically it's not fine as for me
       - [x] Checks for ROOK and KING for the opponent look wrong
       - [x] Fixed old bug: the evaluator encouraged moving one of rooks when there were piece in-between it and a king
       - [x] Thinking for depth 2 reveals issue: comparing 'current' and 'next' situation is not fine when we think for 2'nd ply. Instead we should calculate some absolute value: fixed and extracted 2-ply evaluator for testability.
       - [x] castling safety + 2'nd ply thinking doesn't want castling (since after castling king+rook is moved...)
   - [x] Central control is totally NOT symmetrical. Initially developed in #134
       - [x] Make it symmetrical
       - [x] Ensure Normalized constraints are kept
   - [x] Mobility evaluator is NOT symmetrical. Initially developed in #132 
       - [x] Make it symmetrical
       - [x] Ensure Normalized constraints are kept
       - [x] relative vs absolute values: split to #322
    - [x] Material evaluator IS symmetrical, and shows logical results
    - [x] Protection evaluator is NOT symmetrical
       - [x] Make it symmetrical
       - [x] Ensure Normalized constraints are kept
       - [x] Protection evaluator should strategically protect its pieces even not attacked ones
       - [x] (?) Maybe combine with Attack evaluator - cancelled. It's better to make them independent.
    - [x] Attack evaluator is NOT symmetrical, may be to combine with Protection evaluator
       - [x] Make it symmetrical
       - [x] Ensure Normalized constraints are kept
       - [x] (?) Maybe combine with Protection evaluator - cancelled. It's better to make them independent.
    - [x] Special move evaluator is NOT symmetrical and looks obsolete. Just left comment. No intention to change it - split to #330.
- [x]  Update evaluator factories: make denormalized call normalized - split to #328

- [x] Our engine is smart enough to resign if it detects checkmate on the next move :)
- [x] Core improvements
   - [x] 2-ply evaluator extracted
   - [x] 2-ply evaluation also returns values in normalized range
   - [x] Range concept introduced and reused
- [x] Evaluators independence is another interesting characteristic that is probably hard to achieve but it would be desired. to be investigated.

Final Expectation:
- [x] Normalized brain with depth = 2 should prove that it's better than the brain with depth = 1 (see SimulatorIT)
- [x] From human POV the analyzing should be more logical than in 0.4 - results to be improved in #329
- [x] Denormalized brain can be touched or untouched (to be defined). For simplicity we are allowed to do ANYTHING which doesn't break logical correctness.

**Comment by lrozenblyum** [comment]
Reported an issue https://github.com/fluxroot/jcpi/issues/116 due to which our build fails
